version: '3.8'

services:
  clientapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
    depends_on:
      - serverapp
    extra_hosts:
      - "localhost:host-gateway"
    x-develop:
      watch:
        - action: rebuild
        - path: .
    networks:
      - default

  serverapp:
    build:
      context: ./server21
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./server:/app/server
    depends_on:
      - postgres
    extra_hosts:
      - "localhost:host-gateway"
    x-develop:
      watch:
        - action: rebuild
        - path: .
    networks:
      - default

  #######################
  # Config Kong DB-mode #
  #######################

  # kong-bootstrap:
  #   image: kong:latest
  #   hostname: kong-bootstrap
  #   container_name: kong-bootstrap
  #   depends_on:
  #     - postgres
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: db
  #     KONG_PG_DATABASE: logintp
  #     KONG_PG_USER: postgres
  #     KONG_PG_PASSWORD: password
  #   command: "kong migrations bootstrap"
  #   restart: 'on-failure'

  # kong:
  #   image: kong:latest
  #   hostname: kong
  #   container_name: kong
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"
  #     - "8443:8443"
  #     - "8001:8001"
  #     - "8444:8444"
  #     - "8002:8002"
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: db
  #     KONG_PG_DATABASE: logintp
  #     KONG_PG_USER: postgres
  #     KONG_PG_PASSWORD: password
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  #     KONG_ADMIN_GUI_PATH: /manager
  #     KONG_ADMIN_GUI_URL: http://localhost:8002/manager
  #   command: "kong start --vv"
  #   extra_hosts:
  #     - "localhost:host-gateway"
  #   networks:
  #     - default

  #########################################
  # Config Kong DBless / declarative mode #
  #########################################

  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: kong_nodb
    networks:
      - default
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8000"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"

  postgres:
    image: postgres:latest
    container_name: applogin-db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ./postgredb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logintp
      PGHOST: db
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - default

volumes:
  postgres_db:
    driver: local
    
networks:
  default:
    name: kong-net
