version: '3.8'

services:
  db:
    container_name: applogin-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: kilian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logintp
      PGHOST: db